=== Reikaa/neural-networks/data/project.xsd
<?xml version="1.0"?>
  <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    
    <xsd:element name="project">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element ref="ftse"/>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>

    <xsd:element name="ftse">
      <xsd:complexType>
        <xsd:sequence>
          <xsd:element name="date" minOccurs="0" type="xsd:timeInstant"/>
          <xsd:element name="indexValue" minOccurs="0" type="xsd:double"/>
        </xsd:sequence>
      </xsd:complexType>
    </xsd:element>

  </xsd:schema>

=== Reikaa/neural-networks/data/Forecast5.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="project.xsl"?>
<project xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:noNamespaceSchemaLocation="project.xsd">
<ftse>
<date>2004-07-05</date>
<indexValue>4403.2998</indexValue>
</ftse>
<ftse>
<date>2004-07-06</date>
<indexValue>4370.7002</indexValue>
</ftse>
<ftse>
<date>2004-07-07</date>
<indexValue>4358.3999</indexValue>
</ftse>
<ftse>
<date>2004-07-08</date>
<indexValue>4381.1001</indexValue>
</ftse>
<ftse>
<date>2004-07-09</date>
<indexValue>4393.2002</indexValue>
</ftse>
</project>
